export const workExperience = {
  header: "Experience",
  experience: [
    {
      id: "001",
      position: "Software Developer",
      location: "Remote",
      company: {
        name: "aardosolutions.com",
        url: "https://aardosolutions.com",
      },
      duration: {
        start: "September 2024",
        end: "Present",
      },
      responsibilities: [
        "Developed and maintained scalable web applications to enhance user engagement and operational efficiency.",
        "Hosted and managed servers on AWS EC2, configured domains, and implemented SSL certificates for secure access.",
        "Collaborated with cross-functional teams to design and implement scalable solutions.",
        "Utilized modern frameworks and libraries to ensure responsive and dynamic user interfaces.",
      ],
      technologies: [
        "TypeScript",
        "React.js",
        "Next.js",
        "Tailwind CSS",
        "ShadCN",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Firebase",
        "Contentful",
        "AWS",
        "GCP",
        "Vercel",
        "Nginx",
        "Git & GitHub",
      ],
    },
    {
      id: "002",
      position: "Software Developer",
      location: "Hybrid - Delhi, India",
      company: {
        name: "aardosolutions.com",
        url: "https://aardosolutions.com",
      },
      duration: {
        start: "September 2024",
        end: "Present",
      },
      responsibilities: [
        "Developed and maintained scalable web applications to enhance user engagement and operational efficiency.",
        "Hosted and managed servers on AWS EC2, configured domains, and implemented SSL certificates for secure access.",
        "Collaborated with cross-functional teams to design and implement scalable solutions.",
        "Utilized modern frameworks and libraries to ensure responsive and dynamic user interfaces.",
      ],
      technologies: [
        "TypeScript",
        "React.js",
        "Next.js",
        "Tailwind CSS",
        "ShadCN",
        "Node.js",
        "Express.js",
        "MongoDB",
        "Firebase",
        "Contentful",
        "AWS",
        "GCP",
        "Vercel",
        "Nginx",
        "Git & GitHub",
      ],
    },
  ],
};
